간혹 gpg keyboxd 초기화가 되지 않아 IO 에러가 발생하던 문제 수정

diff --git a/Specific/Windows/WSL/git b/Specific/Windows/WSL/git
--- a/Specific/Windows/WSL/git
+++ b/Specific/Windows/WSL/git
@@ -5,6 +5,7 @@ currentPath="$(pwd)"
 
 echo "$(readlink -f "$currentPath")" | grep "/mnt/" &> /dev/null
 if [ $? -ne 0 ]; then
+# WSL executable binary files
     if [ "$target" == "git" ]; then
         if [ -x /usr/bin/git ]; then
             /usr/bin/git --version | grep "windows" &> /dev/null
@@ -25,6 +26,7 @@ if [ $? -ne 0 ]; then
         fi
     fi
 else
+# Windows executable binary files
     if [ "$target" == "git" ]; then
         if [ -x /usr/bin/git_win ]; then
             /usr/bin/git_win --version | grep "windows" &> /dev/null
@@ -39,6 +41,12 @@ else
             /usr/bin/gpg_win --version | grep Home | awk -F ': ' '{ print $2 }' | grep -E '^/c/Users/'
             if [ $? -eq 0 ]; then
                 /usr/bin/gpg_win $@
+                if [ $? == 1 ]; then
+                    echo 'Unexpected error occurred.' >&2
+                    echo 'Try again `gpg $@` commands with `git-bash.exe` to avoid keybox IO error.' >&2
+                    /mnt/c/Program\ Files/Git/git-bash.exe -c "echo 'Initializing...'"
+                    /usr/bin/gpg_win $@
+                fi
             else
                 exit 1
             fi
