일부 오류 메시지의 경우 stderr 로 표시되도록 수정

diff --git a/Specific/Windows/WSL/gitVI_update b/Specific/Windows/WSL/gitVI_update
--- a/Specific/Windows/WSL/gitVI_update
+++ b/Specific/Windows/WSL/gitVI_update
@@ -11,12 +11,13 @@ if [ -r "/mnt/c/Program Files/Git/usr/bin/vim.exe" ]; then
             if [ ! -r "/mnt/c/Program Files/Git/usr/bin/vim.exe" ]; then
                 echo "gitVI_update: Successfully changed vim.exe to vim-legacy.exe."
             else
-                echo "gitVI_update: Access denied. Please run the script again and accept the UAC prompt."
+                echo "gitVI_update: Access denied. Please run the script again and accept the UAC prompt." >&2
                 exit 1
             fi
         else
-            echo "gitVI_update: Failed to talk UAC daemon. no such file or directory. "
-            echo "gitVI_update: Permission denied. Run the script again with Windows administrator privileges. (aka. UAC)"
+            echo "gitVI_update: Failed to talk UAC daemon. no such file or directory. " >&2
+            echo "gitVI_update: please clone Chronial/wsl-sudo repository in ~/.shellscript to simplify workflow." >&2
+            echo "gitVI_update: Permission denied. Run the script again with Windows administrator privileges. (aka. UAC)" >&2
             exit 1
         fi
     else
@@ -29,8 +30,8 @@ else
     if [ -r "/mnt/c/Program Files/Git/usr/bin/vim-legacy.exe" ]; then
         echo "gitVI_update: Requirement already satisfied."
     else
-        echo "gitVI_update: /mnt/c/Program Files/Git/usr/bin/vim.exe: no such file or directory."
-        echo "gitVI_update: Please check git installed in: C:/Program Files/Git"
+        echo "gitVI_update: /mnt/c/Program Files/Git/usr/bin/vim.exe: no such file or directory." >&2
+        echo "gitVI_update: Please check git installed in: C:/Program Files/Git" >&2
         exit 1
     fi
 fi
