`archlinux.org` 와 연결이 불가능할 경우 `mirrorlist` 파일이 비워지던 문제 수정

diff --git a/Specific/Linux/General/extension b/Specific/Linux/General/extension
--- a/Specific/Linux/General/extension
+++ b/Specific/Linux/General/extension
@@ -87,6 +87,21 @@ if [ -d ~/snap/snd-hda-codec-cs8409 ]; then
     fi
 fi
 
+which pacman &> /dev/null
+if [ $? -eq 0 ]; then
+    ping -c 1 -W 1 -q "archlinux.org" &> /dev/null
+    if [ $? -eq 0 ]; then
+        curl -s 'https://archlinux.org/mirrorlist/?country=KR&country=JP&protocol=https&use_mirror_status=on' | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - | sudo tee /etc/pacman.d/mirrorlist
+    else
+        echo 'error: unable to connect `archlinux.org`. internal error occurred'
+    fi
+fi
+
+which eos-rankmirrors &> /dev/null
+if [ $? -eq 0 ]; then
+    sudo eos-rankmirrors
+fi
+
 if [ "$USE_FULL_UPGRADE" == "true" ]; then
     which pip3 &>/dev/null
     if [ $? == 0 ]; then
@@ -97,10 +112,5 @@ if [ "$USE_FULL_UPGRADE" == "true" ]; then
         fi
     fi
     echo -e "\n"
-fi
-
-which pacman &> /dev/null
-if [ $? -eq 0 ]; then
-    curl -s 'https://archlinux.org/mirrorlist/?country=KR&country=JP&protocol=https&use_mirror_status=on' | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - | sudo tee /etc/pacman.d/mirrorlist
 fi
 
