디렉토리 정렬 및 원격 화면 잠금기능 추가

diff --git a/Specific/Linux/General/obs b/Specific/Linux/General/obs
--- a/Specific/Linux/General/obs
+++ b/Specific/Linux/General/obs
@@ -3,17 +3,17 @@
 window_server=$(inxi -G | grep Display | awk '{ print $2 }')
 if [ "$window_server" == "x11" ]; then
     if [ -n "$DISCORD_BOT_PLAYERCTL" ]; then
-        /usr/bin/python "$HOME/Documents/Release/ShellScript/Universal/OBS Studio/discord-bot.py" 2>&1 &
+        /usr/bin/python "$HOME/Documents/Release/ShellScript/Universal/Discord/obs-recording-stopped.py" 2>&1 &
         bot_pid=$!
         if [ -r /proc/$bot_pid/exe ]; then
             /usr/bin/obs --disable-shutdown-check $@
             kill $bot_pid
         else
-            echo 'error: unable to load `discord-bot.py`. see output.' >&2
+            echo 'error: unable to load `obs-recording-stopped.py`. see output.' >&2
             exit 1
         fi
     else
-        echo 'error: unable to load `discord-bot.py`. API Key is missing.' >&2
+        echo 'error: unable to load `obs-recording-stopped.py`. API Key is missing.' >&2
         notify-send --action='1=OK' 'Unable to launch obs-studio.' 'The Discord API Key does not set yet. Please enter your API Key in `DISCORD_BOT_PLAYERCTL` environment value.'
         exit 1
     fi
