예외처리 및 마이너 버그 수정

diff --git a/Specific/Linux/General/systemctl-install b/Specific/Linux/General/systemctl-install
--- a/Specific/Linux/General/systemctl-install
+++ b/Specific/Linux/General/systemctl-install
@@ -97,8 +97,15 @@ elif [ $# -eq 3 ]; then
     fi
 fi
 
-echo -n "Are you wish to continue install $1? (y/N) > "
-read n
+systemctl --quiet is-enabled $target_name.$1
+if [ $? -eq 4 ]; then
+    echo -n "Are you wish to continue install $1? (y/N) > "
+    read n
+else
+    echo "Unit $target_name.$1 is already exist. Using systemctl function."
+    sudo systemctl edit $target_name.$1
+    exit 1
+fi
 if ! [ "$n" == "Y" -o "$n" == "y" ]; then
     echo "Abort."
     exit 1
@@ -133,7 +140,7 @@ case $1 in
     ;;
 esac
 
-echo "# Generated by systemd-inst., Copyright (c) 2024 Hyeongmin Kim." > /tmp/systemd-inst-$launch_date
+echo "# Generated by systemd-inst., Copyright (c) $(date +'%Y') Hyeongmin Kim." > /tmp/systemd-inst-$launch_date
 echo "# For more infomation $1 syntax, follow this url: https://www.freedesktop.org/software/systemd/man/devel/systemd.$1.html" >> /tmp/systemd-inst-$launch_date
 echo "" >> /tmp/systemd-inst-$launch_date
 echo "[Unit]" >> /tmp/systemd-inst-$launch_date
@@ -147,6 +154,9 @@ case $1 in
     "service")
         echo "[Service]" >> /tmp/systemd-inst-$launch_date
         echo "Type=simple" >> /tmp/systemd-inst-$launch_date
+        echo "# Restart=on-failure" >> /tmp/systemd-inst-$launch_date
+        echo "# RestartSec=5" >> /tmp/systemd-inst-$launch_date
+        echo "# StartLimitIntervalSec=0" >> /tmp/systemd-inst-$launch_date
         echo "# User=$USER" >> /tmp/systemd-inst-$launch_date
         echo "# Group=$USER" >> /tmp/systemd-inst-$launch_date
         echo '# Environment="DISPLAY=:0"' >> /tmp/systemd-inst-$launch_date
@@ -207,10 +217,24 @@ case $1 in
     ;;
 esac
 
-echo -n "Would you like edit your $target_name.$1 config file? (y/N) > "
-read n
+if ! [ x$target_path == x ]; then
+    echo -n "Would you like edit your $target_name.$1 config file? (y/N) > "
+    read n
+else
+    n=y
+fi
 if [ "$n" == "y" -o "$n" == "Y" ]; then
+    cp /tmp/systemd-inst-$launch_date /tmp/systemd-inst-$launch_date.bak
     vi /tmp/systemd-inst-$launch_date
+    cmp -s /tmp/systemd-inst-$launch_date /tmp/systemd-inst-$launch_date.bak
+    if [ $? -eq 0 ]; then
+        rm /tmp/systemd-inst-$launch_date
+        rm /tmp/systemd-inst-$launch_date.bak
+        echo 'Abort.'
+        exit 1
+    else
+        rm /tmp/systemd-inst-$launch_date.bak
+    fi
 fi
 
 if [ $# -eq 2 ]; then
@@ -239,4 +263,5 @@ read n
 if ! [ "$n" == "N" -o "$n" == "n" ]; then
     sudo systemctl start $target_name.$1
 fi
+systemctl status $target_name.$1
 
